name: qdk
channels:
  - conda-forge
  - microsoft
dependencies:
  - python=3.9
  - qsharp
  - networkx
  - rdkit
  - pip
  - jupyter
  - pytest
  - ipywidgets
  - ruamel.yaml
  - varname
  - pip:
    - basis_set_exchange
    - jupyter_jsmol
    - jupyter_client<7.0
    - pyzmq<20.0.0
    - qiskit-qir>=0.3.0a1,<0.4
